<a href="https://colab.research.google.com/github/DavidArroyoTorres/python-ml-course/blob/master/notebooks/T1%20-%202%20-%20Data%20Cleaning%20-%20An%C3%A1lisis%20Preliminar%20de%20los%20Datos-Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive

# Resumen de los datos: dimensiones y estructuras

In [1]:
import pandas as pd
import os
!git clone https://github.com/DavidArroyoTorres/python-ml-course/

Cloning into 'python-ml-course'...
remote: Enumerating objects: 17792, done.
remote: Counting objects: 100% (34/34), done.
remote: Compressing objects: 100% (28/28), done.
remote: Total 17792 (delta 18), reused 6 (delta 6), pack-reused 17758 (from 2)
Receiving objects: 100% (17792/17792), 530.53 MiB | 22.56 MiB/s, done.
Resolving deltas: 100% (358/358), done.
Updating files: 100% (16940/16940), done.

In [2]:
mainpath = "/content/drive/My Drive/Curso Machine Learning con Python/datasets"
filename = "titanic/titanic3.csv"
fullpath = os.path.join(mainpath, filename)

urldata = "https://raw.githubusercontent.com/joanby/python-ml-course/master/datasets/titanic/titanic3.csv"

In [3]:
data = pd.read_csv(urldata)

In [6]:
data.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"

In [ ]:
data.tail(8)

      pclass  survived                       name  ... boat   body  home.dest
1301       3         0       Youseff, Mr. Gerious  ...  NaN  312.0        NaN
1302       3         0          Yousif, Mr. Wazli  ...  NaN    NaN        NaN
1303       3         0      Yousseff, Mr. Gerious  ...  NaN    NaN        NaN
1304       3         0       Zabour, Miss. Hileni  ...  NaN  328.0        NaN
1305       3         0      Zabour, Miss. Thamine  ...  NaN    NaN        NaN
1306       3         0  Zakarian, Mr. Mapriededer  ...  NaN  304.0        NaN
1307       3         0        Zakarian, Mr. Ortin  ...  NaN    NaN        NaN
1308       3         0         Zimmerman, Mr. Leo  ...  NaN    NaN        NaN

[8 rows x 14 columns]

In [ ]:
data.shape

(1309, 14)

In [ ]:
data.columns.values

array(['pclass', 'survived', 'name', 'sex', 'age', 'sibsp', 'parch',
       'ticket', 'fare', 'cabin', 'embarked', 'boat', 'body', 'home.dest'],
      dtype=object)

Vamos a hacer un resumen de los estadísticos básicos de las variables numéricas.

In [ ]:
data.describe()

            pclass     survived  ...         fare        body
count  1309.000000  1309.000000  ...  1308.000000  121.000000
mean      2.294882     0.381971  ...    33.295479  160.809917
std       0.837836     0.486055  ...    51.758668   97.696922
min       1.000000     0.000000  ...     0.000000    1.000000
25%       2.000000     0.000000  ...     7.895800   72.000000
50%       3.000000     0.000000  ...    14.454200  155.000000
75%       3.000000     1.000000  ...    31.275000  256.000000
max       3.000000     1.000000  ...   512.329200  328.000000

[8 rows x 7 columns]

In [ ]:
data.dtypes

pclass         int64
survived       int64
name          object
sex           object
age          float64
sibsp          int64
parch          int64
ticket        object
fare         float64
cabin         object
embarked      object
boat          object
body         float64
home.dest     object
dtype: object

# Missing values

In [ ]:
pd.isnull(data["body"])

0        True
1        True
2        True
3       False
4        True
        ...
1304    False
1305     True
1306    False
1307     True
1308     True
Name: body, Length: 1309, dtype: bool

In [ ]:
pd.notnull(data["body"])

0       False
1       False
2       False
3        True
4       False
        ...
1304     True
1305    False
1306     True
1307    False
1308    False
Name: body, Length: 1309, dtype: bool

In [63]:
pd.isnull(data[["body","age"]]).values.ravel()

array([ True, False,  True, ..., False,  True, False])

In [16]:
pd.notnull(data["body"]).values.ravel().sum()

np.int64(121)

Los valores que faltan en un data set pueden venir por dos razones:
* Extracción de los datos
* Recolección de los datos

#### Borrado de valores que faltan

In [ ]:
data.dropna(axis=0, how="all")

      pclass  survived  ...   body                        home.dest
0          1         1  ...    NaN                     St Louis, MO
1          1         1  ...    NaN  Montreal, PQ / Chesterville, ON
2          1         0  ...    NaN  Montreal, PQ / Chesterville, ON
3          1         0  ...  135.0  Montreal, PQ / Chesterville, ON
4          1         0  ...    NaN  Montreal, PQ / Chesterville, ON
...      ...       ...  ...    ...                              ...
1304       3         0  ...  328.0                              NaN
1305       3         0  ...    NaN                              NaN
1306       3         0  ...  304.0                              NaN
1307       3         0  ...    NaN                              NaN
1308       3         0  ...    NaN                              NaN

[1309 rows x 14 columns]

In [ ]:
data2 = data

In [ ]:
data2.dropna(axis=0, how="any")

Empty DataFrame
Columns: [pclass, survived, name, sex, age, sibsp, parch, ticket, fare, cabin, embarked, boat, body, home.dest]
Index: []

#### Cómputo de los valores fantantes

In [ ]:
data3 = data

In [ ]:
data3.fillna(0)

      pclass  survived  ...   body                        home.dest
0          1         1  ...    0.0                     St Louis, MO
1          1         1  ...    0.0  Montreal, PQ / Chesterville, ON
2          1         0  ...    0.0  Montreal, PQ / Chesterville, ON
3          1         0  ...  135.0  Montreal, PQ / Chesterville, ON
4          1         0  ...    0.0  Montreal, PQ / Chesterville, ON
...      ...       ...  ...    ...                              ...
1304       3         0  ...  328.0                                0
1305       3         0  ...    0.0                                0
1306       3         0  ...  304.0                                0
1307       3         0  ...    0.0                                0
1308       3         0  ...    0.0                                0

[1309 rows x 14 columns]

In [ ]:
data4 = data

In [ ]:
data4= data4.fillna("Desconocido")

In [ ]:
data5 = data

In [ ]:
data5["body"] = data5["body"].fillna(0)
data5["home.dest"] = data5["home.dest"].fillna("Desconocido")
data5.head(5)

   pclass  survived  ...   body                        home.dest
0       1         1  ...    0.0                     St Louis, MO
1       1         1  ...    0.0  Montreal, PQ / Chesterville, ON
2       1         0  ...    0.0  Montreal, PQ / Chesterville, ON
3       1         0  ...  135.0  Montreal, PQ / Chesterville, ON
4       1         0  ...    0.0  Montreal, PQ / Chesterville, ON

[5 rows x 14 columns]

In [ ]:
pd.isnull(data5["age"]).values.ravel().sum()

263

In [ ]:
data5["age"].fillna(data["age"].mean())

0       29.000000
1        0.916700
2        2.000000
3       30.000000
4       25.000000
          ...
1304    14.500000
1305    29.881135
1306    26.500000
1307    27.000000
1308    29.000000
Name: age, Length: 1309, dtype: float64

In [ ]:
data5["age"][1291]

nan

In [ ]:
data5["age"].fillna(method="ffill")

0       29.0000
1        0.9167
2        2.0000
3       30.0000
4       25.0000
         ...
1304    14.5000
1305    14.5000
1306    26.5000
1307    27.0000
1308    29.0000
Name: age, Length: 1309, dtype: float64

In [ ]:
data5["age"].fillna(method="backfill")

0       29.0000
1        0.9167
2        2.0000
3       30.0000
4       25.0000
         ...
1304    14.5000
1305    26.5000
1306    26.5000
1307    27.0000
1308    29.0000
Name: age, Length: 1309, dtype: float64

# Variables dummy

In [ ]:
data["sex"].head(10)

0    female
1      male
2    female
3      male
4    female
5      male
6    female
7      male
8    female
9      male
Name: sex, dtype: object

In [ ]:
dummy_sex = pd.get_dummies(data["sex"], prefix="sex")

In [ ]:
dummy_sex.head(10)

   sex_female  sex_male
0           1         0
1           0         1
2           1         0
3           0         1
4           1         0
5           0         1
6           1         0
7           0         1
8           1         0
9           0         1

In [ ]:
column_name=data.columns.values.tolist()
column_name

['pclass',
 'survived',
 'name',
 'sex',
 'age',
 'sibsp',
 'parch',
 'ticket',
 'fare',
 'cabin',
 'embarked',
 'boat',
 'body',
 'home.dest']

In [ ]:
data = data.drop(["sex"], axis = 1)

In [ ]:
data = pd.concat([data, dummy_sex], axis = 1)

In [ ]:
def createDummies(df, var_name):
    dummy = pd.get_dummies(df[var_name], prefix=var_name)
    df = df.drop(var_name, axis = 1)
    df = pd.concat([df, dummy ], axis = 1)
    return df

In [ ]:
createDummies(data3, "sex")

      pclass  survived  ... sex_female  sex_male
0          1         1  ...          1         0
1          1         1  ...          0         1
2          1         0  ...          1         0
3          1         0  ...          0         1
4          1         0  ...          1         0
...      ...       ...  ...        ...       ...
1304       3         0  ...          1         0
1305       3         0  ...          1         0
1306       3         0  ...          0         1
1307       3         0  ...          0         1
1308       3         0  ...          0         1

[1309 rows x 15 columns]